version: "3.3"
services:
  web:
    container_name: web
    stdin_open: True
    tty: True
    build:
      context: "."
    restart: always
    expose:
      - 8000
    command: ./runserver.sh
    depends_on:
      - redis
    environment:
      - "STATIC_ROOT=/tmp/static-data"
      - "MEDIA_ROOT=/tmp/media-data"
      - "REDIS_URL=redis://redis:6379/1"
    volumes:
      - "media:/tmp/media-data/:rw"
      - "static:/tmp/static-data/:rw"
  nginx:
    container_name: nginx
    stdin_open: True
    tty: True
    image: nginx:1.17.5-alpine
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:rw"
      - "./nginx/nginx-snippet-https.conf:/etc/nginx/nginx-snippet-https.conf:rw"
      - "static:/tmp/static-data:rw"
      - "media:/tmp/media-data:rw"
      - "logs:/tmp/logs-data:rw"
      - "web_root:/var/www/html:rw"
      - "certbot_etc:/etc/letsencrypt:rw"
      - "certbot_var:/var/lib/letsencrypt:rw"
    depends_on:
      - web
    ports:
      - 80:8000
      - 443:443
  ## Container to run redis
  redis:
    container_name: redis
    stdin_open: True
    tty: True
    image: redis:5.0.6-alpine
    restart: always

  # ## Use this container to obtain letsecrypt certs
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot
  #   stdin_open: True
  #   tty: True
  #   command: certonly -n --webroot --webroot-path=/var/www/html --agree-tos -m a@a.com --force-renewal -d ab593cba.ngrok.io
  #   volumes:
  #     - "web_root:/var/www/html:rw"
  #     - "certbot_etc:/etc/letsencrypt:rw"
  #     - "certbot_var:/var/lib/letsencrypt:rw"
  #   depends_on:
  #     - nginx

volumes:
  media:
  static:
  logs:
  web_root:
  certbot_etc:
  certbot_var:
